-- AC Silver's GYM - persistence extension for backend-only endpoints.
-- Run this in Supabase SQL Editor if the base schema already exists.

create table if not exists public."CONFIGURACION_GIMNASIO" (
  id_config bigint primary key default 1,
  capacidad_total integer not null default 30,
  capacidad_por_hora integer not null default 10,
  updated_at timestamptz not null default now(),
  constraint "CONFIGURACION_GIMNASIO_single_row" check (id_config = 1)
);

create table if not exists public."HORARIOS_SERVICIO" (
  id_horario_servicio bigint generated by default as identity primary key,
  servicio text not null,
  codigo_dia text not null default 'LUN',
  dia text not null default 'lunes',
  hora_inicio text not null default '06:00',
  hora_fin text not null default '07:00',
  cupos integer not null default 10,
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public."MATRICULAS_HORARIO" (
  id_matricula bigint generated by default as identity primary key,
  id_cliente bigint not null references public."CLIENTES"("id_cliente") on delete cascade,
  id_horario_servicio bigint not null references public."HORARIOS_SERVICIO"(id_horario_servicio) on delete cascade,
  fecha_matricula date not null default current_date,
  estado text not null default 'ACTIVA',
  created_at timestamptz not null default now()
);

create unique index if not exists "MATRICULAS_HORARIO_activa_unique"
on public."MATRICULAS_HORARIO" (id_cliente, id_horario_servicio)
where estado = 'ACTIVA';

create table if not exists public."MOV_INV" (
  id_mov bigint generated by default as identity primary key,
  id_item bigint not null references public."INVENTARIO"("id_item") on delete cascade,
  id_usuario bigint references public."USUARIO"("id_usuario") on delete set null,
  tipo_movimiento text not null,
  fecha_movimiento date not null default current_date,
  descripcion text not null default '',
  cantidad integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public."TICKETS_ATENCION" (
  id_ticket bigint generated by default as identity primary key,
  id_cliente bigint not null references public."CLIENTES"("id_cliente") on delete cascade,
  id_usuario bigint references public."USUARIO"("id_usuario") on delete set null,
  tipo_ticket text not null,
  descripcion text not null default '',
  estado_ticket text not null default 'Abierto',
  fecha_emitido date not null default current_date,
  fecha_cierre date,
  created_at timestamptz not null default now()
);

alter table public."ASISTENCIA"
  add column if not exists servicio text not null default 'fitness',
  add column if not exists id_usuario_registra bigint references public."USUARIO"("id_usuario") on delete set null,
  add column if not exists id_matricula bigint references public."MATRICULAS_HORARIO"(id_matricula) on delete set null,
  add column if not exists id_horario_servicio bigint references public."HORARIOS_SERVICIO"(id_horario_servicio) on delete set null,
  add column if not exists hora_entrada text not null default '',
  add column if not exists hora_salida text not null default '';

create index if not exists "MATRICULAS_HORARIO_cliente_idx" on public."MATRICULAS_HORARIO" (id_cliente);
create index if not exists "MOV_INV_item_idx" on public."MOV_INV" (id_item);
create index if not exists "TICKETS_ATENCION_cliente_idx" on public."TICKETS_ATENCION" (id_cliente);

insert into public."CONFIGURACION_GIMNASIO" (id_config, capacidad_total, capacidad_por_hora)
values (1, 30, 10)
on conflict (id_config) do nothing;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'CONFIGURACION_GIMNASIO',
    'HORARIOS_SERVICIO',
    'MATRICULAS_HORARIO',
    'MOV_INV',
    'TICKETS_ATENCION'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);

    execute format('drop policy if exists "dev_select_%s" on public.%I', table_name, table_name);
    execute format('drop policy if exists "dev_insert_%s" on public.%I', table_name, table_name);
    execute format('drop policy if exists "dev_update_%s" on public.%I', table_name, table_name);
    execute format('drop policy if exists "dev_delete_%s" on public.%I', table_name, table_name);

    execute format('create policy "dev_select_%s" on public.%I for select to anon, authenticated using (true)', table_name, table_name);
    execute format('create policy "dev_insert_%s" on public.%I for insert to anon, authenticated with check (true)', table_name, table_name);
    execute format('create policy "dev_update_%s" on public.%I for update to anon, authenticated using (true) with check (true)', table_name, table_name);
    execute format('create policy "dev_delete_%s" on public.%I for delete to anon, authenticated using (true)', table_name, table_name);
  end loop;
end $$;

grant usage on schema public to service_role;
grant select, insert, update, delete on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

notify pgrst, 'reload schema';
