-- AC Silver's GYM - Supabase schema compatible with the backend adapter.
-- Run this file in the Supabase SQL Editor before starting the backend.
--
-- The frontend currently calls uppercase table names and accented columns
-- exactly as written here, for example "Duración", "Validación" and
-- "Contraseña". Keep the double quotes unless the frontend is refactored too.

create table if not exists public."PLANES_MEMBRESIA" (
  "id_PM" bigint generated by default as identity primary key,
  "Nombre_Plan" text not null unique,
  "Duración" text not null default '30 dias',
  "Precio" numeric(10,2) not null default 0,
  "Activo" boolean not null default true,
  "created_at" timestamptz not null default now()
);

create table if not exists public."CLIENTES" (
  "id_cliente" bigint generated by default as identity primary key,
  "Nombres" text not null default '',
  "Apellidos" text not null default '',
  "DNI" text not null default '',
  "Telefono" numeric,
  "Email" text not null default '',
  "Correo" text not null default '',
  password_hash text not null default '',
  "Fecha_Registro" date not null default current_date,
  "Estado" boolean not null default false,
  "Plan" text not null default 'MENSUAL',
  "created_at" timestamptz not null default now()
);

create index if not exists "CLIENTES_DNI_idx" on public."CLIENTES" ("DNI");
create index if not exists "CLIENTES_Correo_idx" on public."CLIENTES" ("Correo");
create index if not exists "CLIENTES_password_email_idx" on public."CLIENTES" ("Correo", password_hash);

create table if not exists public."MEMBRESIA" (
  "id_membresia" bigint generated by default as identity primary key,
  "Fecha_Inicio" date not null default current_date,
  "Fecha_Fin" date not null default current_date,
  "Estado" text not null default 'PENDIENTE_PAGO',
  "id_cliente" bigint not null references public."CLIENTES"("id_cliente") on delete cascade,
  "id_PM" bigint references public."PLANES_MEMBRESIA"("id_PM") on delete set null,
  "created_at" timestamptz not null default now()
);

create index if not exists "MEMBRESIA_id_cliente_idx" on public."MEMBRESIA" ("id_cliente");

create table if not exists public."USUARIO" (
  "id_usuario" bigint generated by default as identity primary key,
  "Nombre" text not null default '',
  "Correo" text not null default '',
  "Telefono" text not null default '',
  "DNI" text not null default '',
  "Contraseña" text not null default '',
  "Rol" text not null default 'staff',
  "Estado" boolean not null default true,
  "created_at" timestamptz not null default now()
);

alter table public."CLIENTES"
  add column if not exists password_hash text not null default '';

alter table public."USUARIO"
  add column if not exists "Nombre" text not null default '',
  add column if not exists "Correo" text not null default '',
  add column if not exists "Telefono" text not null default '';

create index if not exists "USUARIO_Correo_idx" on public."USUARIO" ("Correo");

create table if not exists public."INVENTARIO" (
  "id_item" bigint generated by default as identity primary key,
  "Nombre_item" text not null default '',
  "Tipo" text not null default 'General',
  "Cantidad_Stock_E" integer not null default 0,
  "Estado" text not null default 'Operativo',
  "N_ACTIVO" integer,
  "created_at" timestamptz not null default now()
);

create table if not exists public."TIENDA_PRODUCTOS" (
  "id_producto" bigint generated by default as identity primary key,
  "nombre_Producto" text not null default '',
  "categoria" text not null default 'General',
  "precio_Venta" numeric(10,2) not null default 0,
  "cantidad_stock" integer not null default 0,
  "stock_minimo" integer not null default 5,
  "created_at" timestamptz not null default now()
);

create table if not exists public."VENTAS" (
  "id_venta" bigint generated by default as identity primary key,
  "Fecha_Venta" date not null default current_date,
  "total_Venta" numeric(10,2) not null default 0,
  "metodo_Pago" text not null default 'tarjeta',
  "created_at" timestamptz not null default now()
);

create table if not exists public."DETALLE_VENTA" (
  "id_detalle" bigint generated by default as identity primary key,
  "id_venta" bigint not null references public."VENTAS"("id_venta") on delete cascade,
  "id_producto" bigint not null references public."TIENDA_PRODUCTOS"("id_producto") on delete restrict,
  "Cantidad" integer not null default 1,
  "Precio_Unitario" numeric(10,2) not null default 0,
  "Subtotal" numeric(10,2) not null default 0,
  "created_at" timestamptz not null default now()
);

create table if not exists public."ASISTENCIA" (
  "id_asistencia" bigint generated by default as identity primary key,
  "id_cliente" bigint not null references public."CLIENTES"("id_cliente") on delete cascade,
  "id_membresia" bigint references public."MEMBRESIA"("id_membresia") on delete set null,
  "Fecha" date not null default current_date,
  "Hora" text not null default to_char(now(), 'HH24:MI'),
  "Validación" boolean not null default true,
  "created_at" timestamptz not null default now()
);

create index if not exists "ASISTENCIA_Fecha_idx" on public."ASISTENCIA" ("Fecha" desc);

create table if not exists public."CATALOGO_RUTINA" (
  "id_rutina" bigint generated by default as identity primary key,
  "Nombre_rutina" text not null default '',
  "Zonas_musculares" text not null default '',
  "Color" text not null default 'Azul',
  "created_at" timestamptz not null default now()
);

create table if not exists public."HORARIO" (
  "id_horario" bigint generated by default as identity primary key,
  "id_cliente" bigint not null references public."CLIENTES"("id_cliente") on delete cascade,
  "id_rutina" bigint not null references public."CATALOGO_RUTINA"("id_rutina") on delete restrict,
  "Dia_semana" text not null default 'Lunes',
  "Hora_inicio" text not null default '06:00',
  "Hora_fin" text not null default '07:00',
  "created_at" timestamptz not null default now()
);

create table if not exists public."CONFIGURACION_GIMNASIO" (
  id_config bigint primary key default 1,
  capacidad_total integer not null default 30,
  capacidad_por_hora integer not null default 10,
  updated_at timestamptz not null default now(),
  constraint "CONFIGURACION_GIMNASIO_single_row" check (id_config = 1)
);

create table if not exists public."HORARIOS_SERVICIO" (
  id_horario_servicio bigint generated by default as identity primary key,
  servicio text not null,
  codigo_dia text not null default 'LUN',
  dia text not null default 'lunes',
  hora_inicio text not null default '06:00',
  hora_fin text not null default '07:00',
  cupos integer not null default 10,
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public."MATRICULAS_HORARIO" (
  id_matricula bigint generated by default as identity primary key,
  id_cliente bigint not null references public."CLIENTES"("id_cliente") on delete cascade,
  id_horario_servicio bigint not null references public."HORARIOS_SERVICIO"(id_horario_servicio) on delete cascade,
  fecha_matricula date not null default current_date,
  estado text not null default 'ACTIVA',
  created_at timestamptz not null default now()
);

create unique index if not exists "MATRICULAS_HORARIO_activa_unique"
on public."MATRICULAS_HORARIO" (id_cliente, id_horario_servicio)
where estado = 'ACTIVA';

create table if not exists public."MOV_INV" (
  id_mov bigint generated by default as identity primary key,
  id_item bigint not null references public."INVENTARIO"("id_item") on delete cascade,
  id_usuario bigint references public."USUARIO"("id_usuario") on delete set null,
  tipo_movimiento text not null,
  fecha_movimiento date not null default current_date,
  descripcion text not null default '',
  cantidad integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public."TICKETS_ATENCION" (
  id_ticket bigint generated by default as identity primary key,
  id_cliente bigint not null references public."CLIENTES"("id_cliente") on delete cascade,
  id_usuario bigint references public."USUARIO"("id_usuario") on delete set null,
  tipo_ticket text not null,
  descripcion text not null default '',
  estado_ticket text not null default 'Abierto',
  fecha_emitido date not null default current_date,
  fecha_cierre date,
  created_at timestamptz not null default now()
);

alter table public."ASISTENCIA"
  add column if not exists servicio text not null default 'fitness',
  add column if not exists id_usuario_registra bigint references public."USUARIO"("id_usuario") on delete set null,
  add column if not exists id_matricula bigint references public."MATRICULAS_HORARIO"(id_matricula) on delete set null,
  add column if not exists id_horario_servicio bigint references public."HORARIOS_SERVICIO"(id_horario_servicio) on delete set null,
  add column if not exists hora_entrada text not null default '',
  add column if not exists hora_salida text not null default '';

create index if not exists "MATRICULAS_HORARIO_cliente_idx" on public."MATRICULAS_HORARIO" (id_cliente);
create index if not exists "MOV_INV_item_idx" on public."MOV_INV" (id_item);
create index if not exists "TICKETS_ATENCION_cliente_idx" on public."TICKETS_ATENCION" (id_cliente);

insert into public."PLANES_MEMBRESIA" ("Nombre_Plan", "Duración", "Precio", "Activo")
values
  ('MENSUAL', '30 dias', 0, true),
  ('3 MESES', '90 dias', 0, true),
  ('ANUAL', '365 dias', 0, true)
on conflict ("Nombre_Plan") do update set
  "Duración" = excluded."Duración",
  "Activo" = excluded."Activo";

insert into public."CONFIGURACION_GIMNASIO" (id_config, capacidad_total, capacidad_por_hora)
values (1, 30, 10)
on conflict (id_config) do nothing;

-- Development RLS policies. Replace these before production if anonymous
-- writes should not be allowed.
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'PLANES_MEMBRESIA',
    'CLIENTES',
    'MEMBRESIA',
    'USUARIO',
    'INVENTARIO',
    'TIENDA_PRODUCTOS',
    'VENTAS',
    'DETALLE_VENTA',
    'ASISTENCIA',
    'CATALOGO_RUTINA',
    'HORARIO',
    'CONFIGURACION_GIMNASIO',
    'HORARIOS_SERVICIO',
    'MATRICULAS_HORARIO',
    'MOV_INV',
    'TICKETS_ATENCION'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);

    execute format('drop policy if exists "dev_select_%s" on public.%I', table_name, table_name);
    execute format('drop policy if exists "dev_insert_%s" on public.%I', table_name, table_name);
    execute format('drop policy if exists "dev_update_%s" on public.%I', table_name, table_name);
    execute format('drop policy if exists "dev_delete_%s" on public.%I', table_name, table_name);

    execute format('create policy "dev_select_%s" on public.%I for select to anon, authenticated using (true)', table_name, table_name);
    execute format('create policy "dev_insert_%s" on public.%I for insert to anon, authenticated with check (true)', table_name, table_name);
    execute format('create policy "dev_update_%s" on public.%I for update to anon, authenticated using (true) with check (true)', table_name, table_name);
    execute format('create policy "dev_delete_%s" on public.%I for delete to anon, authenticated using (true)', table_name, table_name);
  end loop;
end $$;

-- Grants required by PostgREST when using the anon/authenticated roles.
-- Prefer SUPABASE_SERVICE_ROLE_KEY on the backend for private deployments.
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- Required when the backend uses SUPABASE_SERVICE_ROLE_KEY through PostgREST.
grant usage on schema public to service_role;
grant select, insert, update, delete on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

alter default privileges in schema public
grant select, insert, update, delete on tables to service_role;

alter default privileges in schema public
grant usage, select on sequences to service_role;

notify pgrst, 'reload schema';
