sonar.projectKey=ac-silvers-gym-frontend
sonar.projectName=AC Silver's GYM - Frontend
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.min.js,**/coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
