sonar.projectKey=ac-silvers-gym-backend
sonar.projectName=AC Silver's GYM - Backend
sonar.sources=.
sonar.exclusions=**/.venv/**,**/__pycache__/**,**/venv/**
sonar.python.coverage.reportPaths=coverage.xml
