-- Ejecutar en Supabase > SQL Editor sobre el esquema actual.
-- Es segura para volver a ejecutar: conserva datos y evita recrear columnas o índices.
begin;

-- El backend calcula el siguiente ID a partir del estado remoto y lo envía en los
-- INSERT. BY DEFAULT mantiene la secuencia, pero también acepta ese ID explícito.
alter table public."CLIENTES"
  alter column id_cliente set generated by default;

alter table public."MEMBRESIA"
  alter column id_membresia set generated by default;

-- Datos necesarios para auditar y recuperar la confirmación de la pasarela.
alter table public."MEMBRESIA"
  add column if not exists estado_pago text,
  add column if not exists metodo_pago text,
  add column if not exists referencia_pago text,
  add column if not exists fecha_pago date,
  add column if not exists monto_pago numeric(10, 2);

-- Conserva el precio aceptado al crear cada membresía. De esta forma, un cambio
-- posterior en el precio del plan no altera la validación de un checkout abierto.
update public."MEMBRESIA" as membresia
set monto_pago = plan."Precio"
from public."PLANES_MEMBRESIA" as plan
where membresia.monto_pago is null
  and membresia."id_PM" = plan."id_PM";

update public."MEMBRESIA"
set estado_pago = case
  when upper(coalesce("Estado", '')) in ('ACTIVA', 'ACTIVO', 'EN_TRAMITE') then 'PAGADO'
  else 'PENDIENTE'
end
where estado_pago is null;

update public."MEMBRESIA"
set fecha_pago = created_at::date
where estado_pago = 'PAGADO'
  and fecha_pago is null;

alter table public."MEMBRESIA"
  alter column estado_pago set default 'PENDIENTE',
  alter column estado_pago set not null;

create unique index if not exists membresia_referencia_pago_unique
  on public."MEMBRESIA" (referencia_pago)
  where referencia_pago is not null and referencia_pago <> '';

comment on column public."MEMBRESIA".estado_pago is
  'Estado confirmado del pago: PENDIENTE o PAGADO.';
comment on column public."MEMBRESIA".metodo_pago is
  'Pasarela o método utilizado para pagar la membresía.';
comment on column public."MEMBRESIA".referencia_pago is
  'Identificador único de la sesión devuelto por la pasarela de pago.';
comment on column public."MEMBRESIA".fecha_pago is
  'Fecha en que el backend confirmó el pago con la pasarela.';
comment on column public."MEMBRESIA".monto_pago is
  'Importe esperado que quedó fijado al crear la membresía.';

commit;
