-- Ejecutar en Supabase > SQL Editor después de 001_add_membership_payment_fields.sql.
-- Reutiliza CATALOGO_RUTINA, HORARIOS_SERVICIO y MATRICULAS_HORARIO.
-- La función y el trigger hacen que la reserva del último cupo sea atómica.
begin;

-- El backend conserva IDs explícitos para las altas administrativas. BY DEFAULT
-- mantiene la secuencia de PostgreSQL y también permite esos IDs.
alter table public."CATALOGO_RUTINA"
  alter column id_rutina set generated by default;

alter table public."HORARIOS_SERVICIO"
  alter column id_horario_servicio set generated by default;

alter table public."MATRICULAS_HORARIO"
  alter column id_matricula set generated by default;

-- Alinea las secuencias con los IDs que ya existan antes de empezar a usar los
-- valores automáticos (especialmente la RPC de matrícula).
select setval(
  pg_get_serial_sequence('public."CATALOGO_RUTINA"', 'id_rutina'),
  greatest(coalesce((select max(id_rutina) from public."CATALOGO_RUTINA"), 0), 1),
  exists(select 1 from public."CATALOGO_RUTINA")
);

select setval(
  pg_get_serial_sequence('public."HORARIOS_SERVICIO"', 'id_horario_servicio'),
  greatest(coalesce((select max(id_horario_servicio) from public."HORARIOS_SERVICIO"), 0), 1),
  exists(select 1 from public."HORARIOS_SERVICIO")
);

select setval(
  pg_get_serial_sequence('public."MATRICULAS_HORARIO"', 'id_matricula'),
  greatest(coalesce((select max(id_matricula) from public."MATRICULAS_HORARIO"), 0), 1),
  exists(select 1 from public."MATRICULAS_HORARIO")
);

update public."HORARIOS_SERVICIO"
set cupos = 1
where cupos is null or cupos < 1;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'horarios_servicio_cupos_positivos'
      and conrelid = 'public."HORARIOS_SERVICIO"'::regclass
  ) then
    alter table public."HORARIOS_SERVICIO"
      add constraint horarios_servicio_cupos_positivos check (cupos >= 1);
  end if;
end
$$;

-- Una actualización administrativa de cupos usa el mismo bloqueo de fila que
-- las matrículas. Así no puede dejar la capacidad por debajo de los inscritos.
create or replace function public.validar_capacidad_horario_servicio()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  matriculas_activas bigint;
begin
  select count(*)
  into matriculas_activas
  from public."MATRICULAS_HORARIO" as matricula
  where matricula.id_horario_servicio = new.id_horario_servicio
    and upper(trim(coalesce(matricula.estado, ''))) = 'ACTIVA';

  if new.cupos < matriculas_activas then
    raise exception using
      errcode = 'P0001',
      message = 'No puedes reducir cupos por debajo de los matriculados';
  end if;

  return new;
end
$$;

drop trigger if exists validar_capacidad_horario_servicio_trigger
  on public."HORARIOS_SERVICIO";

create trigger validar_capacidad_horario_servicio_trigger
before update of cupos
on public."HORARIOS_SERVICIO"
for each row
execute function public.validar_capacidad_horario_servicio();

revoke all on function public.validar_capacidad_horario_servicio()
  from public, anon, authenticated;

-- Si hubiera duplicados históricos activos, conserva como activa la matrícula
-- más reciente y marca las demás como canceladas sin borrar registros.
with duplicadas as (
  select
    id_matricula,
    row_number() over (
      partition by id_cliente, id_horario_servicio
      order by id_matricula desc
    ) as posicion
  from public."MATRICULAS_HORARIO"
  where upper(trim(coalesce(estado, ''))) = 'ACTIVA'
)
update public."MATRICULAS_HORARIO" as matricula
set estado = 'CANCELADA'
from duplicadas
where matricula.id_matricula = duplicadas.id_matricula
  and duplicadas.posicion > 1;

create unique index if not exists matriculas_horario_cliente_horario_activa_unique
  on public."MATRICULAS_HORARIO" (id_cliente, id_horario_servicio)
  where upper(trim(coalesce(estado, ''))) = 'ACTIVA';

create or replace function public.validar_cupo_matricula_horario()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  horario_activo boolean;
  horario_cupos integer;
  cupos_usados bigint;
  matricula_actual bigint;
begin
  if upper(trim(coalesce(new.estado, ''))) <> 'ACTIVA' then
    return new;
  end if;

  if tg_op = 'UPDATE' then
    matricula_actual := old.id_matricula;
  end if;

  -- Todas las reservas de un mismo horario se serializan sobre esta fila.
  select horario.activo, horario.cupos
  into horario_activo, horario_cupos
  from public."HORARIOS_SERVICIO" as horario
  where horario.id_horario_servicio = new.id_horario_servicio
  for update;

  if not found or not coalesce(horario_activo, false) then
    raise exception using errcode = 'P0001', message = 'Horario no disponible';
  end if;

  if not exists (
    select 1
    from public."MEMBRESIA" as membresia
    where membresia.id_cliente = new.id_cliente
      and upper(trim(coalesce(membresia."Estado", ''))) in ('ACTIVA', 'ACTIVO')
      and membresia."Fecha_Inicio" <= current_date
      and membresia."Fecha_Fin" >= current_date
  ) then
    raise exception using errcode = 'P0001', message = 'Cliente sin membresia activa';
  end if;

  if exists (
    select 1
    from public."MATRICULAS_HORARIO" as matricula
    where matricula.id_cliente = new.id_cliente
      and matricula.id_horario_servicio = new.id_horario_servicio
      and upper(trim(coalesce(matricula.estado, ''))) = 'ACTIVA'
      and (matricula_actual is null or matricula.id_matricula <> matricula_actual)
  ) then
    raise exception using errcode = 'P0001', message = 'El cliente ya esta matriculado en este horario';
  end if;

  select count(*)
  into cupos_usados
  from public."MATRICULAS_HORARIO" as matricula
  where matricula.id_horario_servicio = new.id_horario_servicio
    and upper(trim(coalesce(matricula.estado, ''))) = 'ACTIVA'
    and (matricula_actual is null or matricula.id_matricula <> matricula_actual);

  if cupos_usados >= horario_cupos then
    raise exception using errcode = 'P0001', message = 'Horario sin cupos disponibles';
  end if;

  return new;
end
$$;

drop trigger if exists validar_cupo_matricula_horario_trigger
  on public."MATRICULAS_HORARIO";

create trigger validar_cupo_matricula_horario_trigger
before insert or update of id_cliente, id_horario_servicio, estado
on public."MATRICULAS_HORARIO"
for each row
execute function public.validar_cupo_matricula_horario();

revoke all on function public.validar_cupo_matricula_horario()
  from public, anon, authenticated;

create or replace function public.matricular_cliente_horario(
  p_id_cliente bigint,
  p_id_horario_servicio bigint
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  matricula public."MATRICULAS_HORARIO"%rowtype;
begin
  -- El trigger valida cliente, membresía, duplicado y cupo dentro de esta misma
  -- transacción, antes de insertar el registro.
  insert into public."MATRICULAS_HORARIO" (
    id_cliente,
    id_horario_servicio,
    estado
  ) values (
    p_id_cliente,
    p_id_horario_servicio,
    'ACTIVA'
  )
  returning * into matricula;

  return to_jsonb(matricula);
end
$$;

comment on function public.matricular_cliente_horario(bigint, bigint) is
  'Matricula un cliente de forma atómica, respetando membresía, duplicados y cupos.';

-- La operación se invoca exclusivamente desde el backend con service_role.
revoke all on function public.matricular_cliente_horario(bigint, bigint)
  from public, anon, authenticated;
grant execute on function public.matricular_cliente_horario(bigint, bigint)
  to service_role;

commit;
